FDN-2397:Upgrade scala v2.13.13 and sbt version upgrade
flowcommerce/dependency pull request #758
Opened 2024-05-24 13:31 UTC by abhidwivedi2701

In this PR we are upgrading scala version from v2.13.10 to v2.13.13 and sbt version from v1.9.9 to v1.10.0 for which need to add type annotation in the below files

 api/app/actors/TaskActor.scala
 api/test/util/DependencySpec.scala
 www/app/lib/Permissions.scala

2024-05-24 13:32 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-24 13:46 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-24 14:03 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-24 14:19 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-24 14:26 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-24 14:33 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-24 14:37 UTC, flow-tech commented
Click here for code coverage report: https://jenkins.flo.pub/job/flowcommerce/job/dependency/job/PR-758/6/scoverage-report/

2024-05-27 10:28 UTC, gheine commented on api/app/actors/TaskActor.scala
> +      case _: TaskDataSyncLibrariesByPrefix => true
Why was this necessary?

2024-05-27 10:28 UTC, gheine requested changes
see above

2024-05-27 15:28 UTC, gheine commented on api/app/actors/TaskActor.scala
> +      case _: TaskDataSyncLibrariesByPrefix => true
Oh that was actually wrong and the updated compiler helped to catch it! Amazing!

2024-05-27 15:31 UTC, gheine approved these changes

2024-05-27 15:35 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 15:39 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 15:47 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 15:52 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 16:04 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 16:09 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 16:14 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 16:25 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 16:34 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 16:44 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 16:52 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 17:03 UTC, gheine approved these changes

2024-05-27 17:26 UTC, flow-tech commented
helm diff detected no changes for dependency-api

helm diff detected no changes for dependency-www

2024-05-27 17:30 UTC, flow-tech commented
Click here for code coverage report: https://jenkins.flo.pub/job/flowcommerce/job/dependency/job/PR-758/20/scoverage-report/

2024-05-28 07:18 UTC, gheine approved these changes

2024-05-28 08:13 UTC, arias-m approved these changes

2024-05-28 08:38 UTC, merged